# Generated by Django 4.1.7 on 2023-03-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
    ]
